- hosts: wordpress
  gather_facts: False
  become: yes

  tasks:
  - name: 'Instalando o Python3'
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  
  roles:
    - server
    - php
    - mysql
    - wordpress