---
# tasks file for mysql
- name: Criando MySQL DB
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes

- name: Criando Usuario MySQL
  mysql_user: 
        name={{ wp_mysql_user }}
        password={{ wp_mysql_password }}
        priv=*.*:ALL
  become: yes
