---
# tasks file for server
- name: Update apt cache
  apt: updat_cache=ys cache_valid_time=3600
  become: ys

- name: Install requird software
  apt: name={{ item }} state=present
  become: yes
  with_items:
          - apache2
          - mysql-server
          - php7.2-mysql
          - php7.2
          - libapache2.mod-php7.2
          - python-mysqldb

